name: Build pack
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Install and Build
      run: |
        npm i -g electron-builder@^21.2.0
        npm i
        npm run pack-nomodule
    - name: Upload file
      uses: actions/upload-artifact@v2
      with:
        name: packs
        path: packs
  
